# file for roles variables
tower_username: "{{ lookup('hashi_vault', 'secret=tower/data/tower:username token='\"{{ vault_token }}\" ' url=http://tklx00002.k24.lan:8200 validate_certs=False') }}"
tower_password: "{{ lookup('hashi_vault', 'secret=tower/data/tower:password token='\"{{ vault_token }}\" ' url=http://tklx00002.k24.lan:8200 validate_certs=False') }}"
tower_host: "{{ lookup('hashi_vault', 'secret=tower/data/tower:host token='\"{{ vault_token }}\" ' url=http://tklx00002.k24.lan:8200 validate_certs=False') }}"
