# main tasks file
---
- name: GATE | Run GATE
  include: gate.yml 

- name: MAIN | Include add_user
  include: add_user.yml
  when: > 
    add_user is defined
    and add_user

- name: MAIN | Include remove_user
  include: remove_user.yml
  when: >
    remove_user is defined
    and remove_user
